config/routes.rb
Rails.application.routes.draw do

root "welcome#index"
resources :waiters
resources :customers
resources :foods

post "/assign_table" => "tables#assign"
post "/sessions" => "sessions#create", as: :sessions_post
delete "/sessions" => "sessions#destroy", as: :sessions_delete
delete "/tables"    =>  "tables#destroy", as: :table_delete

delete "/tables/:table_id/association" => "tables#destroy_association", as: :destroy_association

resources :tables do
  resources :orders
end

end

app/models/customer.rb
class Customer < ActiveRecord::Base

  belongs_to :table
  has_many :orders
  has_many :foods, through: :orders
end

app/models/food.rb
class Food < ActiveRecord::Base

  belongs_to :table
  has_many :customers, through: :orders

end

app/models/order.rb
class Order < ActiveRecord::Base

  belongs_to :food
  belongs_to :customer

end

app/models/table.rb
class Table < ActiveRecord::Base

  belongs_to :waiter
  has_many :customers
  has_many :orders, through: :customers

end

app/models/waiter.rb
class Waiter < ActiveRecord::Base
  has_secure_password
  has_many :tables
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  include SessionsHelper

  before_action :authenticate!, only: [:profile]

  def index
    @customers = Customer.all
  end

  def create
    customer = Customer.create customer_params
    redirect_to new_customer_path
  end

  def new
    @customer = Customer.new
    @table = Table.all
  end

  def show
    @customer = Customer.find params[:id]
  end

#Cant remove the assocition between the table and the waiter
  def destroy
    Customer.destroy params #[not sure what to put in the params]
    redirect_to customers_path
  end


private

def customer_params
  params.require(:customer).permit(:name, :table_id, :order_id)
end



end #End of customers controller

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  include SessionsHelper

  before_action :authenticate!, only: [:profile]

  def create
    food = Food.create(customer_params)
    redirect_to new_food_path
  end

  def new
    @food = Food.new
    @table = Table.all
  end

#Cant remove the assocition between the table and the waiter
  def destroy
    Food.destroy params#[not sure what to put in the params]
    redirect_to customers_path
  end


private

def customer_params
  params.require(:food).permit(:name, :price, :order_id)
end



end #End of customers controller

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  include SessionsHelper

  before_action :authenticate!, only: [:profile]

  def index
    @table     = Table.find(params[:table_id])
    @orders    = @table.orders
    @customers = Customer.all
    @foods     = Food.all
  end

  def create
    order = Order.create order_params
    redirect_to table_orders_path
  end

  def new
    @order     = Order.new
    @customers = Customer.all
    @foods     = Food.all
  end

  def edit
    @order = Order.find params[:id]
  end

  def show
    @order = Order.find params[:id]
  end

  def update
    order = Order.find params[:id]
    Order.update #Again not sure what to put in here
    redirect_to table_path order.id
  end

#Cant remove the assocition between the Order and the waiter
  def destroy
    Order.destroy params #Not sure what to put in params
    redirect_to waiters_path
  end


private

  def order_params
    params.require(:order).permit(:customer_id, :food_id)
  end



end #End of tables controller

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  #take the username and the password and confirm that this is a user on my site
  def create
    username = params[:username]
    password = params[:password]
    waiter = Waiter.find_by username: username
    if waiter && waiter.authenticate(password)
      session[:waiter_id] = waiter.id
      redirect_to waiter_path(waiter.id)
    else
      redirect_to root_path
    end
  end

  def destroy
    session[:waiter_id] = nil
    redirect_to root_path
  end

end #end of sessions controller

app/controllers/tables_controller.rb
class TablesController < ApplicationController

  include SessionsHelper

  before_action :authenticate!, only: [:profile]

  def index
    @tables = Table.all
    @table = Table.new
    @waiters = Waiter.all
  end

  def create
    table = Table.create table_params
    redirect_to tables_path
  end

  def new
    @table = Table.new
  end

  def edit
    @table = Table.find params[:id]
  end

  def show
    @table = Table.find params[:id]
  end

  # def update
  #   table = Table.find params[:id]
  #   table.update waiter_id:current_waiter.id
  #   redirect_to table_path table.id
  # end

  def assign
    table = Table.find_by(table_num: params[:table_num])
    table.update waiter_id: current_waiter.id
    redirect_to waiter_path(current_waiter.id)
  end

#Cant remove the assocition between the table and the waiter
  def destroy
    Table.destroy params[waiter_id: current_waiter.id]
    redirect_to waiters_path
  end


private

def table_params
  params.require(:table).permit(:table_num, :waiter_id)
end



end #End of tables controller

app/controllers/waiters_controller.rb
class WaitersController < ApplicationController

  include SessionsHelper

  before_action :authenticate!, only: [:profile]

  def index
    @waiters = Waiter.all
  end

  def new
    @waiter = Waiter.new
  end

  def create
    waiter = Waiter.create waiter_params
    redirect_to root_path waiter.id
  end

  def edit
    @waiter = Waiter.find params[:id]
  end

  def show
    @waiter = Waiter.find params[:id]
  end

  def update
    waiter = Waiter.find params[:id]
    waiter.update waiter_params
    redirect_to waiters_path waiter.id
  end

  def destroy
    Waiter.destroy params[:id]
    redirect_to root_path
  end

  def profile
    # authenticate!
    @waiter = current_waiter
  end

private

def waiter_params
  params.require(:waiter).permit(:username, :password, :password_confirmation)
end



end #End of waiter controller

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


  def index

  end

  def log_in
    
  end



end #End of welcome controller

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def authenticate!
      redirect_to root_path unless current_waiter
    end

    def current_waiter
      @current_waiter = Waiter.find session[:waiter_id]
    end

end

app/views/customers/new.html.erb
<h1>Add new Customer</h1>

<div class="waiter-page">
<div class="form">
<%= form_for @customer do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

<%= button_to "Orders", new_table_order_path(@table), method: :get %>
</div>
</div>

app/views/foods/new.html.erb
<h1>Add new Food item</h1>

<div class="waiter-page">
<div class="form">
<%= form_for @food do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.submit %>
<% end %>

<%= button_to "Orders", new_table_order_path(@table), method: :get %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestApp</title>
  <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Questrial' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orders/index.html.erb
<h1>Orders for Table #<%= @table.table_num %></h1>

<div class="waiter-page">
<div class="form">

  <% @orders.each do |order| %>

    <p>Order for: <%= order %></p>

  <% end %>

  <%= button_to "Create new Order", new_table_order_path(@table.id), method: :get %>

</div>
</div>

app/views/orders/new.html.erb
<h1>Create new Order</h1>

<div class="waiter-page">
<div class="form">
<%= form_for @order, url: table_orders_path do |f| %>

  <%= f.label :customer_id %>
  <%= f.select( :customer_id, options_for_select(@customers.map {|customer| [customer.name, customer.id ]}) ) %>

  <br>

  <%= f.label :food_id %>
  <%= f.select( :food_id, options_for_select( @foods.map{ |food| [food.name, food.id ]}) ) %>
  <br>

  <%= f.submit %>

<% end %>

<%= button_to "Add Customer", new_customer_path, method: :get %>
<%= button_to "Add Food", new_food_path, method: :get %>

</div>
</div>

app/views/tables/index.html.erb
<h1>Assign Tables</h1>

<div class="waiter-page">
<div class="form">
<%= form_tag "/assign_table" do %>

  <%= label_tag "Table #" %>
  <%= select_tag( :table_num, options_for_select( @tables.map{ |table| [table.table_num ]}) ) %>

  <%= submit_tag "Assign Table" %>

<% end %>

<br>

<%= button_to "Create New Table", new_table_path(@table), method: :get %>
</div>
</div>

app/views/tables/new.html.erb
<h1>Add new Table</h1>
<div class="waiter-page">
<div class="form">
<%= form_for @table do |f| %>

  <%= f.label "Table #" %>
  <%= f.text_field :table_num %>

  <%= f.submit %>
<% end %>
</div>
</div>

app/views/waiters/new.html.erb
<h1>Welcome!</h1>
<div class="sign-up">
<div class="form">
  <p>Input Info Below</p>
    <%= form_for @waiter do |f| %>
      <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Add New Waiter", :class => 'waiter-button' %>
</div>

    <% end %>

</div>

app/views/waiters/show.html.erb
<h1>Welcome Back <%= @waiter.username %></h1>

<%= button_to "Log Out", sessions_delete_path, method: :delete%>
<div class="waiter-page">
<div class="form">
<h2>Here Are Your Assigned Tables</h2>
<% @waiter.tables.each do |table| %>

  <h4><%= link_to(table.table_num, table_orders_path(table.id) ) %></h4>


<% end %>

<%= button_to "Assign Table", tables_path, method: :get %>
</div>
</div>

app/views/welcome/index.html.erb
<h1>Who Gives A Hoot!</h1>
<div class="main-page">
  <p>Employee Login</p>

  <%= form_tag '/sessions', method: :post do %>

  <div class="form">
    <%= label_tag :username %>
    <%= text_field_tag :username %>
  </div>
  <div class="form">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>


  <%= submit_tag "Log In", class: 'log-in' %>

  <%end%>

  <%= button_to "Sign Up", new_waiter_path, method: :get, class: 'sign_up' %>
</div>